# Generated by Django 2.0.3 on 2018-03-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GerundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('gerund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Gerund')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectGerund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('gerund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Gerund')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Obj')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Image')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Obj')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('is_plural', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGerund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('gerund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Gerund')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Image')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Obj')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('plural', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('is_regular', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerbGerund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('gerund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Gerund')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Verb')),
            ],
        ),
        migrations.CreateModel(
            name='VerbImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Image')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Verb')),
            ],
        ),
        migrations.CreateModel(
            name='VerbObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=8, default=0.5, max_digits=8)),
                ('ratings', models.IntegerField(default=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Obj')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Verb')),
            ],
        ),
        migrations.AddField(
            model_name='subjectverb',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Verb'),
        ),
        migrations.AddField(
            model_name='gerundimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Image'),
        ),
    ]
