# Generated by Django 2.0.3 on 2018-03-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_plural',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='is_regular',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='plural',
        ),
    ]
