# Generated by Django 2.0.3 on 2018-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20180331_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerund',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gerundimage',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='object',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='objectgerund',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='objectimage',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjectgerund',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjectimage',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjectobject',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjectverb',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='verb',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='verbgerund',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='verbimage',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='verbobject',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
    ]
