# Generated by Django 2.0.3 on 2018-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20180331_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_plural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='is_regular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='plural',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
